{% set name = "Ipopt" %}
{% set version = "3.12.8" %}
{% set sha256 = "54938be9b7398869a7d3974e545117884001847e23939ba0a2c71fa7a898210f" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.coin-or.org/download/pkgsource/{{ name }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - ipopt.patch # [not win]
    - dll_makefile.patch # [win]
build:
  number: 1
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - toolchain # [not win]
    - m2w64-toolchain # [win]
    - ampl-mp  # [not win]
    - mumps
    - metis 5.1.*  # [not win]
    - scotch  # [not win]
    - gcc  # [osx]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - m2w64-openblas # [win]
    - posix # [win]
    - patch # [win]

  run:
    - ampl-mp  # [not win]
    - mumps # [not win]
    - metis 5.1.*  # [not win]
    - scotch  # [not win]
    - libgfortran  # [not win]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]

test:
  files:
    - test
    - mytoy.nl

  requires:
    - toolchain # [not win]
    - m2w64-toolchain # [win]
    - posix # [win]

about:
  home: https://projects.coin-or.org/Ipopt/
  license: EPL 1.0
  license_file: LICENSE
  summary: Software package for large-scale nonlinear optimization

extra:
  recipe-maintainers:
    - pstjohn
    - bluescarni
